# Generated by Django 4.2.3 on 2023-07-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="文件名字/标题")),
                ("path", models.CharField(max_length=100, verbose_name="文件存储路径")),
                ("date", models.DateField(verbose_name="时间")),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.college",
                        verbose_name="所属学院",
                    ),
                ),
            ],
        ),
    ]
